### ISSUE TITLE
Explicit Types needed for certain symbols

### ISSUE THREAD

**Issue by losowski** [losowski/trading#3]
2020-06-04 21:42:33,327 [INFO] Update Check:AAPL: (1960-01-01 00:00:00->2020-06-04): Y
2020-06-04 21:42:33,327 [DEBUG] Start Stamp: 1960-01-01 00:00:00
2020-06-04 21:42:33,327 [DEBUG] End Date Stamp: 2020-06-04
2020-06-04 21:42:33,327 [DEBUG] Date: 1960-01-01 00:00:00
2020-06-04 21:42:33,327 [DEBUG] Year: 1960
2020-06-04 21:42:33,327 [DEBUG] Month: 1
2020-06-04 21:42:33,327 [DEBUG] Day: 1
2020-06-04 21:42:33,327 [DEBUG] Date: 2020-06-04
2020-06-04 21:42:33,328 [DEBUG] Year: 2020
2020-06-04 21:42:33,328 [DEBUG] Month: 6
2020-06-04 21:42:33,328 [DEBUG] Day: 4
2020-06-04 21:42:33,329 [DEBUG] Starting new HTTPS connection (1): finance.yahoo.com:443
2020-06-04 21:42:33,690 [DEBUG] https://finance.yahoo.com:443 "GET /quote/AAPL/history HTTP/1.1" 200 None
2020-06-04 21:42:33,748 [DEBUG] Starting new HTTPS connection (1): query1.finance.yahoo.com:443
2020-06-04 21:42:33,956 [DEBUG] https://query1.finance.yahoo.com:443 "GET /v7/finance/download/AAPL?period1=-315619200&period2=1591228800&interval=1d&events=history&crumb=z4QQN21OO2x HTTP/1.1" 200 None
2020-06-04 21:42:34,050 [INFO] Inserting ['AAPL', '1980-12-12', 0.513393, 0.515625, 0.513393, 0.513393, 0.405683, 117258400.0]
Traceback (most recent call last):
  File "/home/eugene/projects/trading/python/historical/stockBase.py", line 83, in updateQuotes
    self.insertQuote(insertQuery, symbol, dataRows)
  File "/home/eugene/projects/trading/python/historical/yahoo.py", line 49, in insertQuote
    self.rawInsertQuote(dataQuery, symbol, date, openPrice, highPrice, lowPrice, closePrice, adjClosePrice, volume)
  File "/home/eugene/projects/trading/python/historical/stockBase.py", line 119, in rawInsertQuote
    insertQuery.callproc(self.insertQuoteData, dataList)
psycopg2.errors.UndefinedFunction: function trading_schema.pinsquote(unknown, unknown, numeric, numeric, numeric, numeric, numeric, numeric) does not exist
LINE 1: SELECT * FROM trading_schema.pInsQuote('AAPL','1980-12-12',0...
                      ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./stockquote.py", line 21, in <module>
    main()
  File "./stockquote.py", line 14, in main
    feeds.run()
  File "/home/eugene/projects/trading/python/historical/stockBase.py", line 60, in run
    self.updateQuotes()
  File "/home/eugene/projects/trading/python/historical/stockBase.py", line 86, in updateQuotes
    except psycopg2.Error as e:
NameError: name 'psycopg2' is not defined
2020-06-04 21:42:34,070 [INFO] Closing connection to to: trading@tradingdb on localhost:5432
2020-06-04 21:42:34,071 [INFO] ROLLBACK

**Comment by losowski** [comment]
SELECT * FROM trading_schema.pDisableSymbol('AAPL');

**Comment by losowski** [comment]
./symbol.py --symbol=AAPL --enable=N now achieves the same (workaround)

**Comment by losowski** [comment]
UPDATE trading_schema.symbol SET enabled = 'N' WHERE symbol like '%-%';
UPDATE trading_schema.symbol SET enabled = 'N' WHERE symbol like '%.%';
UPDATE trading_schema.symbol SET enabled = 'N' WHERE symbol like '%*%';

These queries take care of the general cases (hyphen and full-stop)

**Comment by losowski** [comment]
Locating problem symbols:
SELECT * from trading_schema.symbol where enabled='N' AND symbol NOT like '%.%' AND symbol NOT like '%-%'  AND symbol NOT like '%*%';

**Comment by losowski** [comment]
Some of these are "preferred stocks"
Yahoo simply does not know about them as the price is the same as common stock (but that has  a a different symbol)

-- List of disabled entries that are NOT preferred:
SELECT * from trading_schema.exchange e INNER JOIN trading_schema.symbol s ON (s.exchange_id = e.id) where e.enabled = 'Y' AND (s.symbol like '%.%' OR s.symbol like '%-%' OR s.symbol like '%*%');

**Comment by losowski** [comment]
This is mostly from Yahoo kicking the connection.
Resolution to restrict polling interval to 2 seconds
