### ISSUE TITLE
Upstream Bug- for ABR-A

### ISSUE THREAD

**Issue by losowski** [losowski/trading#4]
Traceback (most recent call last):
  File "./stockquote.py", line 21, in <module>
    main()
  File "./stockquote.py", line 14, in main
    feeds.run()
  File "/home/eugene/projects/trading/python/historical/stockBase.py", line 66, in run
    self.updateQuotes()
  File "/home/eugene/projects/trading/python/historical/stockBase.py", line 85, in updateQuotes
    dataRows = self.getHistoricalData(symbol,lastUpdate, todayDate, update)
  File "/home/eugene/projects/trading/python/historical/yahoo.py", line 39, in getHistoricalData
    data = yahoo_historical.Fetcher(symbol, sd, ed)
  File "/usr/local/lib/python3.7/dist-packages/yahoo_historical/fetch.py", line 25, in __init__
    self.cookie, self.crumb = self.init()
  File "/usr/local/lib/python3.7/dist-packages/yahoo_historical/fetch.py", line 46, in init
    return cookie, crumb  # return a tuple of crumb and cookie
UnboundLocalError: local variable 'crumb' referenced before assignment

**Comment by losowski** [comment]
Caused by polling too frequently.
Fixed by polling every 2 seconds
