### ISSUE TITLE
Some Symbols unsupported by Yahoo finance

### ISSUE THREAD

**Issue by losowski** [losowski/trading#5]
2020-06-05 21:12:54,010 [DEBUG] https://finance.yahoo.com:443 "GET /quote/ALIT/history HTTP/1.1" 200 None
2020-06-05 21:12:54,127 [DEBUG] Starting new HTTPS connection (1): query1.finance.yahoo.com:443
2020-06-05 21:12:54,234 [DEBUG] https://query1.finance.yahoo.com:443 "GET /v7/finance/download/ALIT?period1=-315619200&period2=1591315200&interval=1d&events=history&crumb=wEpp9uP4d5f HTTP/1.1" 404 38
Traceback (most recent call last):
  File "./stockquote.py", line 21, in <module>
    main()
  File "./stockquote.py", line 14, in main
    feeds.run()
  File "/home/eugene/projects/trading/python/historical/stockBase.py", line 66, in run
    self.updateQuotes()
  File "/home/eugene/projects/trading/python/historical/stockBase.py", line 89, in updateQuotes
    self.insertQuote(insertQuery, symbol, dataRows)
  File "/home/eugene/projects/trading/python/historical/yahoo.py", line 47, in insertQuote
    for date, openPrice, highPrice, lowPrice, closePrice, adjClosePrice, volume in zip(data.get('Date'), data.get('Open'), data.get('High'), data.get('Low'), data.get('Close'), data.get('Adj Close'), data.get('Volume')):
TypeError: zip argument #1 must support iteration
2020-06-05 21:12:54,267 [INFO] Closing connection to to: trading@tradingdb on localhost:5432
2020-06-05 21:12:54,268 [INFO] ROLLBACK

**Comment by losowski** [comment]
./symbol.py --symbol=ALIT --enable=N

Workaround
